### ISSUE TITLE
Can't build with jekyll when deployed by Travis-CI

### ISSUE THREAD

**Issue by OlingCat** [Agda-zh/PLFA-zh#67] opened 2019-07-17 09:17 UTC
At https://travis-ci.org/Agda-zh/PLFA-zh/jobs/559531094#L863, the jekyll report:
```
ruby -S bundle exec jekyll build
Configuration file: /home/travis/build/Agda-zh/PLFA-zh/_config.yml
            Source: /home/travis/build/Agda-zh/PLFA-zh
       Destination: /home/travis/build/Agda-zh/PLFA-zh/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
  Liquid Exception: Liquid syntax error (line 78): Unknown tag 'endraw' in out/tspl/2018/Assignment4.md
jekyll 3.8.5 | Error:  Liquid syntax error (line 78): Unknown tag 'endraw'
make: *** [build] Error 1
The command "make test-offline" exited with 2.
```

But in my local environment there is no such error.
(instead a `htmlproofer 3.11.0 | Error:  HTML-Proofer found 739 failures!`, while it's another problem ╮(╯▽╰)╭)

Do you have any idea? @wenkokke

**Comment by ice1000** [comment] 2019-07-17 09:27
![image](https://user-images.githubusercontent.com/16398479/61364300-69510e00-a83a-11e9-9276-57031be4809c.png)

There's a lot of incorrect `{% endraw %}`s generated

**Comment by ice1000** [comment] 2019-07-17 09:29
```diff
diff --git a/highlight.sh b/highlight.sh
index 2ad478e..33e5951 100755
--- a/highlight.sh
+++ b/highlight.sh
@@ -91,7 +91,7 @@ for INCLUDE_PATH in "$@"; do
                 AGDA_MODULE_SRC="${AGDA_MODULE_SRC#./}"
                 AGDA_MODULE_OUT="$(out_path "$AGDA_MODULE_SRC")"
                 AGDA_MODULE_HTML="$(basename "$(html_path "$AGDA_MODULE_SRC" "$HTML_DIR")" .md).html"
-                echo "s|$AGDA_MODULE_HTML|{% endraw %}{{ site.baseurl }}{% link $AGDA_MODULE_OUT %}{% raw %}|;" >> "$LOCAL_LINKS_SED"
+                echo "s|$AGDA_MODULE_HTML|{{ site.baseurl }}{% link $AGDA_MODULE_OUT %}{% raw %}|;" >> "$LOCAL_LINKS_SED"
             done
         fi
```

**Comment by ice1000** [comment] 2019-07-17 09:41
Maybe Jekyll is ignoring some `endraw`s? I don't see any problems here:

![image](https://user-images.githubusercontent.com/16398479/61365322-5e977880-a83c-11e9-876e-73a77e11011b.png)

**Comment by ice1000** [comment] 2019-07-17 09:42
Cannot reproduce under agda-stdlib master, `agda --version Agda version 2.6.1-129c025`

**Comment by fangyi-zhou** [comment] 2019-07-17 10:00
Retry with Travis works: https://travis-ci.org/Agda-zh/PLFA-zh/jobs/559531094
Closing for now. If it happens again, we shall re-open this issue and investigate.

**Closed by fangyi-zhou** 2019-07-17 10:00 UTC
